# Generated by Django 5.2.1 on 2025-05-21 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategoryModel',
            new_name='SofaCategoryModel',
        ),
    ]
