# Generated by Django 5.2.1 on 2025-05-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sofamodel',
            name='Warranty',
            field=models.IntegerField(choices=[(3, '۳ ماه'), (6, '۶ ماه'), (9, '۹ ماه'), (12, '12 ماه'), (16, '16 ماه'), (18, '18 ماه'), (22, '22 ماه'), (24, '24 ماه')], default=3, null=True),
        ),
        migrations.AddField(
            model_name='sofamodel',
            name='weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
