# Generated by Django 5.2.1 on 2025-07-09 14:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_sofamodel_warranty_sofamodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofamodel',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=200),
        ),
    ]
