# Generated by Django 5.2.1 on 2025-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_sofamodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
