# Generated by Django 5.2.1 on 2025-07-24 21:59

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_sofamodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sofamodel',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=400),
        ),
    ]
