# Generated by Django 5.2.1 on 2025-06-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponmodel',
            old_name='max_limit_usafe',
            new_name='max_limit_usage',
        ),
    ]
