# Generated by Django 5.2.1 on 2025-06-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='ref_ir',
            new_name='ref_id',
        ),
    ]
